// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: 42fd3c2514375fc6ad281552368edd3fb9f6ee7f

package data

// linguist's commit from which files were generated.
var LinguistCommit = "42fd3c2514375fc6ad281552368edd3fb9f6ee7f"
