// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: b5432ebc7e78f25415b98d48c2fbacddbf8df317

package data

// linguist's commit from which files were generated.
var LinguistCommit = "b5432ebc7e78f25415b98d48c2fbacddbf8df317"
