// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: 80f3531e8a1014a23f4606458e5a528053ed3cac

package data

// linguist's commit from which files were generated.
var LinguistCommit = "80f3531e8a1014a23f4606458e5a528053ed3cac"
