// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: b28dd4b0d5ef6bfaca56f1d34571fddef13e3ead

package data

// linguist's commit from which files were generated.
var LinguistCommit = "b28dd4b0d5ef6bfaca56f1d34571fddef13e3ead"
