// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: 3ef386bbb7d10afe2ef81d85c9911871a9f2c221

package data

// linguist's commit from which files were generated.
var LinguistCommit = "3ef386bbb7d10afe2ef81d85c9911871a9f2c221"
