// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: 9b50e9e46bc0fb2451f5deee612a36c386aae6cf

package data

// linguist's commit from which files were generated.
var LinguistCommit = "9b50e9e46bc0fb2451f5deee612a36c386aae6cf"
